# Generated by Django 4.1.2 on 2022-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapi", "0002_alter_todo_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterModelTable(
            name="todo",
            table="todos",
        ),
    ]
